name: Wine Arch Linux CI

on:
  #schedule:
  #  - cron:  '45 8,20 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Install Git
        run: pacman -Sy --noconfirm git
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Compile
        env:
          XDG_CACHE_HOME: /tmp/.cache
        run: |
          pacman -Syu --noconfirm base-devel sudo git freetype2 graphite harfbuzz libpng fontconfig jack2
          useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown user -R .

          ./build-lug-wine.sh ntsync
      - name: Upload Archive
        uses: actions/upload-artifact@v4
        with:
          name: "lug-wine-tkg-build"
          path: ./output
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: "lug-wine-tkg-build"
          path: .
      - name: Find archive
        id: find
        shell: bash {0}
        run: |
          file="$(find . -name '*.tar.gz' | head -n1)"
          version="$(echo $file | grep -oE '[0-9]+\.[0-9]+')"
          echo "ARCHIVE_PATH=$file" >> $GITHUB_OUTPUT
          echo "NEW_TAG=$version" >> $GITHUB_OUTPUT
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.find.outputs.NEW_TAG }}
          files: ${{ steps.find.outputs.ARCHIVE_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}